### ISSUE TITLE
Running tests throws an error on import

### ISSUE THREAD

**Issue by kdoran** [sabarasaba/modern-backbone-starterkit#4]
```
git clone https://github.com/sabarasaba/modern-backbone-starterkit.git
cd modern-backbone-starterkit/
npm i
karma start
```

gives me:

```
Chrome 46.0.2490 (Mac OS X 10.10.5) ERROR
  Uncaught SyntaxError: Unexpected token import
  at /Users/kdoran/Documents/messin/modern-backbone-starterkit/tests/index.js:1
```

Great project by the way, been using it (without tests) and so far really helpful.

**Comment by sabarasaba** [comment]
@kdoran Good call man ! https://github.com/sabarasaba/modern-backbone-starterkit/commit/f73fe9750fb0a4d988280692c121861fbdf233ad should fix it, dependencies got updated with breaking changes, so I just updated them and everything works again ! 

PS: Also added an `npm test` command so that is easier to type than karma start :P
