### ISSUE TITLE
Split App and Vendor Code

### ISSUE THREAD

**Issue by camskene** [sabarasaba/modern-backbone-starterkit#9]
Would it be possible to create a separate bundle for vendor libraries ie. jquery, backbone, etc, and a bundle just for the app code?

I tried adding the configuration in webpack.config as outlined in the docs:
https://webpack.github.io/docs/code-splitting.html#split-app-and-vendor-code

The issues I faced though were: 
1) the vendor.js file is never written to disk (although in the terminal it seems webpack actually creates a vendor.js file)

2) main.js still contains the vendor libraries.

Any thoughts how this could work?

**Comment by sabarasaba** [comment]
Hello, that is indeed something you can do ! Although I wont be adding it the boilerplate as I don't think is a common case for everyone, but feel free to fork and implement it yourself !

While you are reading the right docs for webpack, and webpack is generating the 2 separate bundles your problem is gulp applying the stream to only one of the files (webpackConfig.entry) take a look at https://github.com/sabarasaba/modern-backbone-starterkit/blob/master/gulpfile.js#L30 and I'm sure you'll be able to figure it out :)

**Comment by camskene** [comment]
hmmm, tried for a long time to figure it out with no success :crying_cat_face: :

**Comment by sabarasaba** [comment]
aight, I can give you a hand over the weekend if you want. I'm a bit busy at work atm o/

**Comment by camskene** [comment]
I forked the repo and created a branch with what I thought might work:
https://github.com/camskene/modern-backbone-starterkit/tree/vendor-bundle

If you do `gulp build --type production` you'll see this:

![image](https://cloud.githubusercontent.com/assets/507499/12365227/7517e74c-bba1-11e5-94f2-5493e2cd8b7f.png)

It looks like a separate bundle is created for vendors but no file is written and it looks like bundle.js still contains the vendor code.

When you have time you help is greatly appreciated.
